apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-task-api
  template:
    metadata:
      labels:
        app: devops-task-api
    spec:
      containers:
        - name: devops-task-api
          image: ghcr.io/myclipha/devops-task-api:b9a0bb755b378359204636492a97e957c449f96b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: devops-task-api-config
                  key: APP_ENV
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: devops-task-api-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-task-api-secret
                  key: DB_PASSWORD
