apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-task-api
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: devops-task-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
